Develop a classification model for Iris dataset using  Pseudo  inversemethod  and evaluate the  performance. 

In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
import matplotlib.pyplot as plt

In [2]:
iris.feature_names 

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
#creating a dataframe with columns as feature names
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
#setting the labels of the dataframe

df['target']=iris.target
df.head

<bound method NDFrame.head of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8  

In [6]:
#Splitting the data as input and the target
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

ONE HOT ENCODING

In [7]:
#one hot encoding the target names as 1 or 0.
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder()
#enc.fit(y)
y=enc.fit_transform(Y.values.reshape(-1,1)).toarray()
  
#Merge with main
#y=df.join(enc_df)
  
print(y)




[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

TRAIN-TEST SPLIT

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)
print(X_train.shape)

(120, 4)


In [9]:
#finding the weight matrix
w = np.matmul(np.linalg.pinv(X_train),y_train)

In [10]:
w

array([[ 0.08799632,  0.28378664, -0.21961892],
       [ 0.25374459, -0.3798907 ,  0.21476294],
       [-0.23387486,  0.08355229,  0.11743435],
       [-0.05289505, -0.43469613,  0.45658372]])

In [11]:
y_pred = np.matmul(X_test,w)
y_pred

0         1         2
14   1.234128  0.139723 -0.182500
98   0.323334  0.270076  0.271396
75   0.238907  0.492375  0.350732
16   1.139589 -0.014386 -0.013069
131  0.056811  0.463672  0.745857
56   0.207890  0.231398  0.607594
141  0.079362  0.206782  0.799452
44   0.947490 -0.011402  0.101801
29   0.840787  0.164891 -0.065756
120 -0.035588  0.218925  0.891389
94   0.126852  0.349315  0.436777
5    1.046039  0.019035  0.033905
102 -0.104934  0.455310  0.736683
51   0.243380  0.324525  0.495010
78   0.132058  0.324978  0.518429
42   0.884550  0.054690 -0.035100
92   0.171141  0.470821  0.302232
66   0.122234  0.173474  0.627753
31   0.965941  0.192269 -0.096963
35   0.960735  0.216607 -0.178615
90   0.051192  0.419105  0.415091
84   0.104634  0.116717  0.671677
77   0.091513  0.440476  0.536206
40   1.008182  0.067525 -0.056785
125 -0.052904  0.546474  0.632442
99   0.184413  0.331349  0.424548
33   1.211703 -0.004680 -0.050175
19   1.046330 -0.001353  0.009169
73   0.084577  0.538465  0.361503
146 -0.081137  0.429968  0.607989

In [13]:
#find out the highest value for each row 
maxVal = np.asarray(y_pred.max(axis=1))
maxVal

array([1.23412819, 0.32333359, 0.49237523, 1.1395887 , 0.74585697,
       0.60759389, 0.79945229, 0.94749043, 0.84078662, 0.8913892 ,
       0.43677708, 1.04603876, 0.73668295, 0.49501046, 0.51842915,
       0.88455018, 0.47082051, 0.62775301, 0.96594144, 0.96073546,
       0.41910543, 0.67167679, 0.53620611, 1.00818184, 0.63244196,
       0.42454804, 1.21170323, 1.04632988, 0.53846497, 0.60798896])

In [14]:
# for one hot encoding of the predicted value ,i.e. highest value in each row will be 1 and other will be 0.
for i in range(len(maxVal)):
    for j in range(3):
        
        if y_pred.iloc[i,j] == maxVal[i]:
            y_pred.iloc[i,j] = 1
        else :
            y_pred.iloc[i,j] = 0
            
y_pred.head()

0    1    2
14   1.0  0.0  0.0
98   1.0  0.0  0.0
75   0.0  1.0  0.0
16   1.0  0.0  0.0
131  0.0  0.0  1.0

In [15]:
#Accuracy measures
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score,f1_score

print('Accuracy Score : ', accuracy_score(y_test,y_pred))
print('Precision Score : ', precision_score(y_test,y_pred, average = 'weighted'))
print('Recall Score : ', recall_score(y_test,y_pred,average = 'weighted'))
print('F1 Score : ', f1_score(y_test,y_pred,average = 'weighted'))
print('\n')
print(classification_report(y_test,y_pred))

Accuracy Score :  0.7
Precision Score :  0.8551587301587301
Recall Score :  0.7
F1 Score :  0.6746462063086104


              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.31      0.47        13
           2       0.43      1.00      0.60         6

   micro avg       0.70      0.70      0.70        30
   macro avg       0.78      0.77      0.68        30
weighted avg       0.86      0.70      0.67        30
 samples avg       0.70      0.70      0.70        30

